plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.navigation.safe.args)
    alias(libs.plugins.detekt)
    alias(libs.plugins.ktlint)
}

android {
    namespace "com.rafaelfelipeac.improov"
    compileSdkVersion 35

    buildFeatures {
        compose true
        viewBinding true
        buildConfig true
    }

    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeCompiler.get()
    }

    defaultConfig {
        applicationId "com.rafaelfelipeac.improov"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 23
        versionName "1.8.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            resValue "string", "app_name", "Improov"
            resValue "string", "file_provider_path", "com.rafaelfelipeac.improov.fileprovider"
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'

            resValue "string", "app_name", "Improov Debug"
            resValue "string", "file_provider_path", "com.rafaelfelipeac.improov.debug.fileprovider"
        }
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.resValue "string", "versionName", variant.versionName
    }

    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas")
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Android
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.datastore.preferences
    implementation libs.androidx.activity.compose
    implementation libs.google.material

    // Compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.foundation
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.text
    implementation libs.androidx.compose.ui.tooling.preview
    debugImplementation libs.androidx.compose.ui.tooling

    // Kotlin
    implementation libs.kotlin.stdlib

    // LiveData & ViewModel
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.common.java8

    // Room
    kapt libs.androidx.room.compiler
    implementation libs.androidx.room.runtime

    // Navigation
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.compose

    // Dagger 2
    kapt libs.dagger.compiler
    implementation libs.dagger.runtime

    // DecoView
    implementation libs.decoview

    // GifView
    implementation libs.android.gif.drawable

    // Gson
    implementation libs.gson

    // Coroutines
    implementation libs.kotlinx.coroutines.core

    // Test
    testImplementation libs.junit
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.androidx.arch.core.testing
    testImplementation libs.mockito.inline
    testImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.room.testing
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.ext.junit
    detektPlugins libs.detekt.formatting
}

detekt {
    buildUponDefaultConfig = true
    config.setFrom(files("$rootDir/default-detekt-config.yml"))
    baseline = file("$projectDir/detekt-baseline.xml")
}

ktlint {
    android.set(true)
    baseline.set(file("$projectDir/config/ktlint/baseline.xml"))
    outputToConsole.set(true)
    ignoreFailures.set(false)
}

kapt {
    arguments {
        arg("room.schemaLocation", "$projectDir/schemas")
    }
}
