name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  releaseApk:
    name: Build, Sign and Upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Build .APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v1
        with:
            name: improov-release
            path: ${{ env.SIGNED_RELEASE_FILE }}

      - name: Upload APK to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.rafaelfelipeac.improov
          releaseFile: ${{ env.SIGNED_RELEASE_FILE }}
          track: alpha

      - name: Message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: New apk uploaded to alpha on Google Play Store.
